var System = require("system");
var safeLog = System.safeLog;

var CH = { valve:"A04/K1", p:"905.3/input_1_value", c:"905.3/input_1_current", secBlock:"power_monitor/secondary_alerts_blocked" };
var CFG = { currentBreakMa:3.6, pressureMinBar:1.2, pressureTargetBar:1.5, pressureAlarmBar:0.8, pulseOpenS:3, pulsePauseS:20, maxPulses:5, watchdogS:15, filterSize:3 };
var S = { buf:[], active:false, valveOpening:false, waitingPause:false, pulseCount:0, sensorAlarm:false, lowPressureAlarm:false, makeupFailedAlarm:false, watchdogAlarm:false, lastEvent:"", valveCloseTimer:null, pauseTimer:null, watchdogTimer:null };
function b(v){return v===true||v===1||v==="1"||v==="true";} function n(p,fb){var v=Number(dev[p]); return isNaN(v)?fb:v;} function set(c,v){if(dev["pressure_makeup/"+c]!==v) dev["pressure_makeup/"+c]=v;}
function loge(t){S.lastEvent=t; set("last_event",t); safeLog("[507_Pressure_makeup] "+t);} function clamp(v,a,z){if(v<a)return a;if(v>z)return z;return v;}
function filtered(){var v=n(CH.p,null),i,sum=0;if(v===null)return null; S.buf.push(v); while(S.buf.length>CFG.filterSize)S.buf.shift(); for(i=0;i<S.buf.length;i++)sum+=S.buf[i]; return clamp(sum/S.buf.length,0,6);} 
function closeValve(reason){ if(b(dev[CH.valve])) dev[CH.valve]=false; if(S.valveCloseTimer){clearTimeout(S.valveCloseTimer);S.valveCloseTimer=null;} if(S.watchdogTimer){clearTimeout(S.watchdogTimer);S.watchdogTimer=null;} S.valveOpening=false; if(reason) loge(reason); }
function stopCycle(reason){ closeValve(reason); if(S.pauseTimer){clearTimeout(S.pauseTimer);S.pauseTimer=null;} S.active=false; S.waitingPause=false; }
function settings(){ return {enabled:b(dev["pressure_makeup/enabled"]),auto:b(dev["pressure_makeup/auto_mode"]),min:n("pressure_makeup/pressure_min_bar",CFG.pressureMinBar),target:n("pressure_makeup/pressure_target_bar",CFG.pressureTargetBar),alarm:n("pressure_makeup/pressure_alarm_bar",CFG.pressureAlarmBar),brk:n("pressure_makeup/current_break_ma",CFG.currentBreakMa),openS:n("pressure_makeup/pulse_open_s",CFG.pulseOpenS),pauseS:n("pressure_makeup/pulse_pause_s",CFG.pulsePauseS),max:n("pressure_makeup/max_pulses",CFG.maxPulses),wd:n("pressure_makeup/watchdog_s",CFG.watchdogS)}; }
function openPulse(manual){ var cfg=settings(); if(S.sensorAlarm||S.valveOpening||S.waitingPause||b(dev[CH.valve])) return; S.active=true; S.pulseCount++; S.valveOpening=true; dev[CH.valve]=true; loge(manual?"Открытие клапана: ручной импульс":"Открытие клапана"); S.valveCloseTimer=setTimeout(function(){S.valveCloseTimer=null; closeValve("Закрытие клапана"); S.waitingPause=true; loge("Начало паузы"); S.pauseTimer=setTimeout(function(){S.pauseTimer=null; S.waitingPause=false; loge("Окончание паузы"); evaluate();}, cfg.pauseS*1000); }, cfg.openS*1000); S.watchdogTimer=setTimeout(function(){S.watchdogTimer=null; if(b(dev[CH.valve])){ S.watchdogAlarm=true; stopCycle("Watchdog: аварийное закрытие клапана"); System.sendAlert("Котельная","Аварийное закрытие подпитки","Клапан был открыт дольше допустимого времени.","Проверьте реле и логику подпитки.");}}, cfg.wd*1000); }
function update(){ var p=filtered(), c=n(CH.c,null), cfg=settings(); set("pressure_bar",p); set("pressure_current_ma",c); set("valve_open",b(dev[CH.valve])); set("active",S.active); set("valve_opening",S.valveOpening); set("waiting_pause",S.waitingPause); set("pulse_count",S.pulseCount); set("sensor_alarm",S.sensorAlarm); set("low_pressure_alarm",S.lowPressureAlarm); set("makeup_failed_alarm",S.makeupFailedAlarm); set("watchdog_alarm",S.watchdogAlarm); set("status_line1","Давление: "+p+" бар; ток: "+c+" mA"); set("status_line2","Цикл: "+(S.active?"активен":"остановлен")+", импульсы "+S.pulseCount+"."); set("status_line3","Клапан: "+(b(dev[CH.valve])?"открыт":"закрыт")+"."); set("status_text",S.lastEvent); if(c!==null && c<cfg.brk){S.sensorAlarm=true; stopCycle("Ошибка датчика: ток ниже порога");} if(p!==null && p<cfg.alarm) S.lowPressureAlarm=true; if(p!==null && p>=cfg.min) S.lowPressureAlarm=false; }
function evaluate(){ var p=filtered(), cfg=settings(); update(); if(!cfg.enabled||!cfg.auto){ stopCycle("Подпитка отключена"); return;} if(S.sensorAlarm) return; if(S.valveOpening||S.waitingPause) { if(p!==null&&p>=cfg.target){ stopCycle("Успешное завершение: достигнуто целевое давление"); S.active=false;} return; } if(p!==null&&p>=cfg.target){ if(S.active) stopCycle("Успешное завершение"); S.active=false; S.makeupFailedAlarm=false; return;} if(p!==null&&p<cfg.min){ if(S.pulseCount>=cfg.max){ S.makeupFailedAlarm=true; stopCycle("Неуспешное завершение: превышено количество импульсов"); return;} if(!S.active) loge("Старт цикла подпитки"); openPulse(false);} }

defineVirtualDevice("pressure_makeup",{title:"Подпитка давления",cells:{enabled:{type:"switch",value:true},auto_mode:{type:"switch",value:true},pressure_min_bar:{type:"value",value:CFG.pressureMinBar},pressure_target_bar:{type:"value",value:CFG.pressureTargetBar},pressure_alarm_bar:{type:"value",value:CFG.pressureAlarmBar},current_break_ma:{type:"value",value:CFG.currentBreakMa},pulse_open_s:{type:"value",value:CFG.pulseOpenS},pulse_pause_s:{type:"value",value:CFG.pulsePauseS},max_pulses:{type:"value",value:CFG.maxPulses},watchdog_s:{type:"value",value:CFG.watchdogS},manual_close:{type:"pushbutton"},reset_alarm:{type:"pushbutton"},manual_pulse:{type:"pushbutton"},pressure_bar:{type:"value",readonly:true,value:0},pressure_current_ma:{type:"value",readonly:true,value:0},valve_open:{type:"switch",readonly:true,value:false},active:{type:"switch",readonly:true,value:false},valve_opening:{type:"switch",readonly:true,value:false},waiting_pause:{type:"switch",readonly:true,value:false},pulse_count:{type:"value",readonly:true,value:0},sensor_alarm:{type:"switch",readonly:true,value:false},low_pressure_alarm:{type:"switch",readonly:true,value:false},makeup_failed_alarm:{type:"switch",readonly:true,value:false},watchdog_alarm:{type:"switch",readonly:true,value:false},last_event:{type:"text",readonly:true,value:""},status_line1:{type:"text",readonly:true,value:""},status_line2:{type:"text",readonly:true,value:""},status_line3:{type:"text",readonly:true,value:""},status_text:{type:"text",readonly:true,value:""}}});
defineRule("pressure_makeup_eval_507",{whenChanged:[CH.p,CH.c,"pressure_makeup/enabled","pressure_makeup/auto_mode","pressure_makeup/pressure_min_bar","pressure_makeup/pressure_target_bar","pressure_makeup/current_break_ma","pressure_makeup/pulse_open_s","pressure_makeup/pulse_pause_s","pressure_makeup/max_pulses",CH.secBlock],then:function(){evaluate();}});
defineRule("pressure_makeup_manual_close_507",{whenChanged:"pressure_makeup/manual_close",then:function(v){if(!v)return; stopCycle("Ручное закрытие"); S.active=false; update();}});
defineRule("pressure_makeup_reset_alarm_507",{whenChanged:"pressure_makeup/reset_alarm",then:function(v){if(!v)return; S.sensorAlarm=false;S.makeupFailedAlarm=false;S.watchdogAlarm=false;loge("Сброс аварийного состояния"); update();}});
defineRule("pressure_makeup_manual_pulse_507",{whenChanged:"pressure_makeup/manual_pulse",then:function(v){if(!v)return; if(S.sensorAlarm||b(dev[CH.valve])){loge("Ручной импульс отклонен"); return;} openPulse(true); update();}});
setTimeout(function(){ safeLog("[507_Pressure_makeup] старт скрипта"); dev[CH.valve]=false; loge("Принудительное закрытие клапана на старте"); evaluate(); },3000);
