"""Cable lengths, conduits and AV catalog application API."""

from .domain import (
    CONDUIT_TYPE_CODES,
    LINE_CONDUIT_ATTRIBUTES,
    MOUNT_WAY_BY_ROUTE_METHOD,
    ROUTE_METHOD_BY_MOUNT_WAY,
    TIMBER_CABLE_RESERVE_M,
    TIMBER_CONDUIT_TYPES,
    CableCalculationError,
    CablePointInput,
    ConduitContractError,
    LengthResult,
    RouteMethod,
    calculate_automatic_length,
    calculate_effective_length,
    calculate_segment_length,
    conduit_is_present,
    conduit_type_suffix,
    format_conduit_id,
    parse_conduit_id,
    validate_line_conduit_fields,
)
from .service import CableError, CableService, HdmiSelectionResult

__all__ = [
    "CONDUIT_TYPE_CODES",
    "LINE_CONDUIT_ATTRIBUTES",
    "MOUNT_WAY_BY_ROUTE_METHOD",
    "ROUTE_METHOD_BY_MOUNT_WAY",
    "TIMBER_CABLE_RESERVE_M",
    "TIMBER_CONDUIT_TYPES",
    "CableCalculationError",
    "CableError",
    "CablePointInput",
    "CableService",
    "ConduitContractError",
    "LengthResult",
    "HdmiSelectionResult",
    "RouteMethod",
    "calculate_automatic_length",
    "calculate_effective_length",
    "calculate_segment_length",
    "conduit_is_present",
    "conduit_type_suffix",
    "format_conduit_id",
    "parse_conduit_id",
    "validate_line_conduit_fields",
]
